apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        release: {{ .Release.Name }}
    spec:
      # serviceAccountName: kritis-service-account
      containers:
      - name: {{ .Values.image.name }}
        image: gcr.io/priya-wadhwa/kritis-server:demo
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["--tls-cert-file=/var/tls/cert", "--tls-key-file=/var/tls/key"]
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
        - mountPath: /var/tls
          name: tls
        - name: priyawadhwa-ca-admin
          mountPath: /secret
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/priyawadhwa-ca-admin.json
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}
        - name: priyawadhwa-ca-admin
          secret:
            secretName: priyawadhwa-ca-admin
