apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.serviceName }}
webhooks:
  - name: kritis-validation-hook.grafeas.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6ekNDQXJlZ0F3SUJBZ0lSQUpoU2orMWZYclVpZGU4MzJTckM2K1l3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1lUVmtPRE0wWVdZdFpUZ3hOaTAwWWpaa0xXRmhNR0V0TjJNellUZ3pNek16WVdNMApNQjRYRFRFNE1EY3hNekl3TWprME9Gb1hEVEl6TURjeE1qSXdNamswT0Zvd2RURUxNQWtHQTFVRUJoTUNWVk14CkV6QVJCZ05WQkFnVENsZGhjMmhwYm1kMGIyNHhFREFPQmdOVkJBY1RCMU5sWVhSMGJHVXhEVEFMQmdOVkJBb1QKQkZOMWMyVXhEakFNQmdOVkJBc1RCVU5oWVZOUU1TQXdIZ1lEVlFRREV4ZDBiSE10ZDJWaWFHOXZheTF6WldOeQpaWFF0Ym1GdFpUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5KbTc5K1BqaG9nCjNBTXVuamdINlFOdVVrRGlJZW9sS3FCejZjdDQxd1FuamFkRDhyV0ZZRW00QU1FaldjVE5ZRStjeUpOQW9JQWIKMWVadWxSMkk2OUVIZDhqZktkeFhDYlNYVU8yRWY3TGFVb2s4c0s4RnpOd2FRT3dOb3MwSTFGUy93R1JCU0lPRQpSOUJHQThoTzRQOGg3WS9KdUtQNDFMVWVzdjZCVXlrRXE2LzE3M3IySHFBNFYvc2dMM29LMXNkb25HNmhFY2xFCkpBMzE3MWdHWTNSTklYdWdlVEZCY1AvY3dTanByRVFYTGFYNTBvSTZsZUhWSnpCWS9qTHFaQTlCTmxQUzBVZkgKMUtUWXh2aDNyc0RhTzM4anh0QnBNUzlpV1NKS1N3MTdEMURhMnpMNnBXU2JpZ1hncHFadGhYVmV5VWlXMC9qYwpnSDRWRVFFRjAyY0NBd0VBQWFPQm56Q0JuREFNQmdOVkhSTUJBZjhFQWpBQU1JR0xCZ05WSFJFRWdZTXdnWUNDCkZtdHlhWFJwY3kxMllXeHBaR0YwYVc5dUxXaHZiMnVDSW10eWFYUnBjeTEyWVd4cFpHRjBhVzl1TFdodmIyc3UKYTNWaVpTMXplWE4wWlcyQ0htdHlhWFJwY3kxMllXeHBaR0YwYVc5dUxXaHZiMnN1WkdWbVlYVnNkSUlpYTNKcApkR2x6TFhaaGJHbGtZWFJwYjI0dGFHOXZheTVrWldaaGRXeDBMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUF4Q1RRbmRoZXVoR0UrOG11bklDblVNalVtT29NNU5wc2QxUTJUZmVua2RQUnlRSlZGbXNZNnBtVGViSDgKMGxGcHNOODJmdnpVb3dpUXBqNUp5ZXhRMjFoYTBXV1BRU3NBNGR1Yzh0YWxDZjVYYklPd2JkL0xqWnpCbzFVNgphYXdKaVIzcmVhd3VPTUdPb1B5SUhNdC9JZEIvamhiNWlVM2hDY0dpU09lalRsaTBWR2Y3RmR5QXNkWk1Jd3FWCkl4TzVobTVlTjRiODNMNFJRSHRncEZTMjRFTHdIRjlvQ0x6ejlkNnplUVFzYjE2NTYzeGdhSmxpbnplRi9jeUgKb2VqN0R0SUZWaWtSWGR2dHBZM2h6ajh2NDVnWjZsTmcxbThxVExPK1RzMXBsZFJDT3h0UlFuWjFPR2R1VTZYTQpJd0FRZlVjcTdRUmg0d0hvbGJMMmsraGxhUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: {{ .Values.serviceName }}
        namespace: default
