apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: default
    name: kritis-service-account

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: kritis-clusterrolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    namespace: default
    name: kritis-service-account

# to let the admission server read imagewhitelist/imagesecuritypolicies
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: kritis-clusterrole
    labels:
      # Add these permissions to the "edit" default role, so that "edit" can see our CRD.
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
  rules:
  - apiGroups: ["kritis.grafeas.io"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

# to read the config for terminating authentication
# - apiVersion: rbac.authorization.k8s.io/v1
#   kind: RoleBinding
#   metadata:
#     namespace: kube-system
#     name: extension-server-authentication-reader-kritis
#   roleRef:
#     kind: Role
#     apiGroup: rbac.authorization.k8s.io
#     name: extension-apiserver-authentication-reader
#   subjects:
#   - kind: ServiceAccount
#     namespace: default
#     name: kritis-service-account