steps:
  # Build kritis
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "deploy/Dockerfile",
           "-t", "gcr.io/kritis-project/kritis-server:${COMMIT_SHA}", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "deploy/Dockerfile",
           "-t", "gcr.io/kritis-project/kritis-server:latest", "."]
  # Build preinstall container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "helm-hooks/Dockerfile",
           "-t", "gcr.io/kritis-project/preinstall:${COMMIT_SHA}", ".", "--build-arg", "stage=preinstall"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kritis-project/preinstall:${COMMIT_SHA}", "gcr.io/kritis-project/preinstall:latest"]
  # Build postinstall container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "helm-hooks/Dockerfile",
           "-t", "gcr.io/kritis-project/postinstall:${COMMIT_SHA}", ".", "--build-arg", "stage=postinstall"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kritis-project/postinstall:${COMMIT_SHA}", "gcr.io/kritis-project/postinstall:latest"]
  # Build predelete container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "helm-hooks/Dockerfile",
           "-t", "gcr.io/kritis-project/predelete:${COMMIT_SHA}", ".", "--build-arg", "stage=predelete"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kritis-project/predelete:${COMMIT_SHA}", "gcr.io/kritis-project/predelete:latest"]
  # Build container to build resolve-tags
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "deploy/Dockerfile_resolve",
           "-t", "resolve-tags", "."]
  # Do the go build
  - name: "resolve-tags"
    args: ["make", "cross-tar"]
  # Copy over resolve-tags to bucket
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "out/resolve-tags*", "cmd/kritis/kubectl/plugins/resolve/plugin.yaml", "gs://resolve-tags/$COMMIT_SHA/"]
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://resolve-tags/$COMMIT_SHA/*", "gs://resolve-tags/latest/"]
images: ["gcr.io/kritis-project/kritis-server:${COMMIT_SHA}",
         "gcr.io/kritis-project/kritis-server:latest",
         "gcr.io/kritis-project/preinstall:${COMMIT_SHA}",
         "gcr.io/kritis-project/preinstall:latest",
         "gcr.io/kritis-project/postinstall:${COMMIT_SHA}",
         "gcr.io/kritis-project/postinstall:latest",
         "gcr.io/kritis-project/predelete:${COMMIT_SHA}",
         "gcr.io/kritis-project/predelete:latest"]
